/**
 * ABI Generator Script
 * 
 * Reads contract ABIs from the foundry output and generates a TypeScript file
 * with typed ABIs for use in the backend.
 * 
 * Usage: npx tsx scripts/generate-abis.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const CONTRACT_OUT_DIR = join(__dirname, '..', '..', '..', 'apps', 'contract', 'out');
const OUTPUT_FILE = join(__dirname, '..', 'src', 'types', 'generated.ts');

const CONTRACTS = [
  'VideoRegistry',
  'PredictionMarket', 
  'PointsRegistry'
];

function loadAbi(contractName: string): any[] {
  const abiPath = join(CONTRACT_OUT_DIR, `${contractName}.sol`, `${contractName}.json`);
  try {
    const artifact = JSON.parse(readFileSync(abiPath, 'utf-8'));
    return artifact.abi;
  } catch (error) {
    console.error(`Failed to load ABI for ${contractName} from ${abiPath}:`, error);
    throw error;
  }
}

function generateAbisFile(): void {
  console.log('Generating ABIs from contract artifacts...');
  
  const abis: Record<string, any[]> = {};
  
  for (const contract of CONTRACTS) {
    console.log(`  Loading ${contract}...`);
    abis[contract] = loadAbi(contract);
  }
  
  const output = `/**
 * Generated Contract ABIs
 * 
 * DO NOT EDIT - This file is auto-generated by scripts/generate-abis.ts
 * Run 'npm run gen' to regenerate.
 */

export const videoRegistryAbi = ${JSON.stringify(abis.VideoRegistry, null, 2)} as const;

export const predictionMarketAbi = ${JSON.stringify(abis.PredictionMarket, null, 2)} as const;

export const pointsRegistryAbi = ${JSON.stringify(abis.PointsRegistry, null, 2)} as const;
`;

  writeFileSync(OUTPUT_FILE, output, 'utf-8');
  console.log(`\n✅ Generated ABIs written to ${OUTPUT_FILE}`);
}

generateAbisFile();
