/**
 * Generated Contract ABIs
 * 
 * DO NOT EDIT - This file is auto-generated by scripts/generate-abis.ts
 * Run 'npm run gen' to regenerate.
 */

export const videoRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_pointsRegistry",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "CONVICTION_PERIOD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "UPLOAD_POINTS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "dismissConviction",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "convictionIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "finalizeVideo",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getAllVideoIds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getConviction",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "convictionIndex",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct VideoRegistry.Conviction",
        "components": [
          {
            "name": "challenger",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "walrusBlobId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum VideoRegistry.ConvictionStatus"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getConvictionCount",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getVideo",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct VideoRegistry.VideoIndex",
        "components": [
          {
            "name": "id",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "walrusBlobId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "uploader",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "uploadTime",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "convictionPeriodEnd",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum VideoRegistry.VideoStatus"
          },
          {
            "name": "convictions",
            "type": "tuple[]",
            "internalType": "struct VideoRegistry.Conviction[]",
            "components": [
              {
                "name": "challenger",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "walrusBlobId",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "timestamp",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "status",
                "type": "uint8",
                "internalType": "enum VideoRegistry.ConvictionStatus"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getVideoCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isInConvictionPeriod",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pointsRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract PointsRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolveConviction",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "convictionIndex",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "upheld",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitConviction",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "proofBlobId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "submitIndex",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "walrusBlobId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "ConvictionDismissed",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "convictionIndex",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConvictionResolved",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "convictionIndex",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "upheld",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ConvictionSubmitted",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "convictionIndex",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "challenger",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "walrusBlobId",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "timestamp",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VideoChallenged",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VideoFinalized",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VideoIndexed",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "uploader",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "walrusBlobId",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "uploadTime",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "convictionPeriodEnd",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ConvictionNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ConvictionPeriodActive",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ConvictionPeriodEnded",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyBlobId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyVideoId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidStatus",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VideoAlreadyExists",
    "inputs": []
  },
  {
    "type": "error",
    "name": "VideoNotFound",
    "inputs": []
  }
] as const;

export const predictionMarketAbi = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "_pointsRegistry",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "MARKET_DURATION",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "WINNER_POINTS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "closeMarket",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createMarket",
    "inputs": [
      {
        "name": "videoId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "question",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getActivityCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAllActivities",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct PredictionMarket.Activity[]",
        "components": [
          {
            "name": "activityType",
            "type": "uint8",
            "internalType": "enum PredictionMarket.ActivityType"
          },
          {
            "name": "user",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "marketId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "isYes",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getAllMarketIds",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string[]",
        "internalType": "string[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarket",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PredictionMarket.Market",
        "components": [
          {
            "name": "id",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "videoId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "question",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "createdAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "expiresAt",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "yesVotes",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noVotes",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "resolved",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "winningSide",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "status",
            "type": "uint8",
            "internalType": "enum PredictionMarket.MarketStatus"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarketActivities",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct PredictionMarket.Activity[]",
        "components": [
          {
            "name": "activityType",
            "type": "uint8",
            "internalType": "enum PredictionMarket.ActivityType"
          },
          {
            "name": "user",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "marketId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "isYes",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarketCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarketOdds",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "yesPercentage",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "noPercentage",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getMarketVoters",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPosition",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct PredictionMarket.Position",
        "components": [
          {
            "name": "yesVotes",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "noVotes",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRecentActivities",
    "inputs": [
      {
        "name": "count",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct PredictionMarket.Activity[]",
        "components": [
          {
            "name": "activityType",
            "type": "uint8",
            "internalType": "enum PredictionMarket.ActivityType"
          },
          {
            "name": "user",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "marketId",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "isYes",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "timestamp",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isMarketExpired",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pointsRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract PointsRegistry"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "resolveMarket",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      },
      {
        "name": "winningSide",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "voteNo",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "voteYes",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "internalType": "string"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "MarketClosed",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarketCreated",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "videoId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "question",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "expiresAt",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "MarketResolved",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "winningSide",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "yesVotes",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "noVotes",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "VoteCast",
    "inputs": [
      {
        "name": "marketId",
        "type": "string",
        "indexed": true,
        "internalType": "string"
      },
      {
        "name": "voter",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "isYes",
        "type": "bool",
        "indexed": false,
        "internalType": "bool"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "EmptyQuestion",
    "inputs": []
  },
  {
    "type": "error",
    "name": "EmptyVideoId",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidVoteAmount",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketAlreadyResolved",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketNotExpired",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MarketNotFound",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  }
] as const;

export const pointsRegistryAbi = [
  {
    "type": "constructor",
    "inputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "awardPoints",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "convictionRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPoints",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "predictionMarket",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setContracts",
    "inputs": [
      {
        "name": "_videoRegistry",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_predictionMarket",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "_convictionRegistry",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "videoRegistry",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ContractsSet",
    "inputs": [
      {
        "name": "videoRegistry",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "predictionMarket",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "convictionRegistry",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PointsAwarded",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "reason",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "InvalidAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "Unauthorized",
    "inputs": []
  }
] as const;
